### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PauGuillamon** [redwarp/gifdecoder#13]
Hi,

As I'm trying to use this library in a commercial project, can you please clarify a few things regarding licenses?

Are these benchmark files actually included in the library?
```
benchmark/src/main/java/com/bumptech/glide/gifdecoder/GifDecoder.kt: * Copyright 2014 Google, Inc. All rights reserved.
benchmark/src/main/java/com/bumptech/glide/gifdecoder/GifFrame.kt: * Copyright 2014 Google, Inc. All rights reserved.
benchmark/src/main/java/com/bumptech/glide/gifdecoder/GifHeader.kt: * Copyright 2014 Google, Inc. All rights reserved.
benchmark/src/main/java/com/bumptech/glide/gifdecoder/GifHeaderParser.kt: * Copyright 2014 Google, Inc. All rights reserved.
benchmark/src/main/java/com/bumptech/glide/gifdecoder/StandardGifDecoder.java: * Copyright (c) 2013 Xcellent Creations, Inc.
benchmark/src/main/java/com/bumptech/glide/gifdecoder/StandardGifDecoder.java: * Copyright 2014 Google, Inc. All rights reserved.
```

Is this bitmap.h file from AOSP actually used in the library?
```
giflzwdecoder/ndkheaders/bitmap.h: * Copyright (C) 2009 The Android Open Source Project
```

Any other thing I should take into account regarding the license?

Could also be helpful to clarify this in the README.md file ;) 

Thank you so much!

**Comment by redwarp** [comment]
Hey!

First, that make me happy that this is being used by somebody else than me.

To answer your question, even though I want to emphasize that I'm not a lawyer:

If you use the decoder, or the android-drawable, then all the code inside is Apache 2.

The benchmark library does not get published, I wrote it to compare the performance of my implementation compared to the existing java implementation. So that is the Google part, and I don't think it concerns you.

The header in giflzwdecoder, you can also ignore, as it's part of a separate library, currently in hold, where I wanted to implement the decoding in rust to compare performance between a native+jni implementation and a pure kotlin one.

Sorry if it's a bit messy, and I'm definitely open to suggestions Tu make all of that more clear.

**Comment by redwarp** [comment]
I updated the README, let me know what you think.

**Comment by PauGuillamon** [comment]
Hi, thank you so much for clarifying those topics and updating the README file. I guess this issue can be closed now.

Btw, good job on this project :)
